name: Deploy to GH Pages
on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            # Checkout Repo
            - name: Checkout
              uses: actions/checkout@v3
            # Setup Node
            - name: Setup Node JS
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            # Install Dependencies
            - name: Install Dependencies
              run: npm install
              working-directory: ./frontend
            # Build
            - name: Build
              run: npm run build
              working-directory: ./frontend
            # Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: frontend/dist
